<a href="https://colab.research.google.com/github/galihweb000haha/CNN/blob/main/cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [167]:
import numpy as np
import pandas as pd

In [168]:
data_courses = pd.read_csv('udemy_courses.csv')
data_courses.head()

course_id  ...           subject
0    1070968  ...  Business Finance
1    1113822  ...  Business Finance
2    1006314  ...  Business Finance
3    1210588  ...  Business Finance
4    1011058  ...  Business Finance

[5 rows x 12 columns]

In [169]:
def min_max_scaling(df):
  df_norm = df.copy()
  for column in df_norm.columns:
    df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())
  return df_norm

In [170]:
norm_data_courses = min_max_scaling(data_courses[['price', 'num_subscribers', 'num_reviews', 'num_lectures']])
print(norm_data_courses)

      price  num_subscribers  num_reviews  num_lectures
0     1.000         0.007984     0.000838      0.065469
1     0.375         0.010382     0.033631      0.351733
2     0.225         0.008084     0.002696      0.065469
3     0.475         0.009114     0.000401      0.046213
4     1.000         0.004745     0.001640      0.033376
...     ...              ...          ...           ...
3673  0.500         0.003867     0.000510      0.026958
3674  0.125         0.001138     0.000109      0.053915
3675  0.200         0.001908     0.006158      0.061617
3676  0.250         0.001116     0.001130      0.048780
3677  0.225         0.003350     0.001312      0.025674

[3678 rows x 4 columns]


In [171]:
target_output = data_courses[['level']].replace(['All Levels', 'Beginner Level', 'Intermediate Level', 'Expert Level'], [0, 1, 2, 3])
print(target_output)

      level
0         0
1         0
2         2
3         0
4         2
...     ...
3673      0
3674      1
3675      0
3676      0
3677      1

[3678 rows x 1 columns]


In [172]:
norm_data_courses = pd.concat([norm_data_courses, target_output], axis=1)
print(norm_data_courses)

      price  num_subscribers  num_reviews  num_lectures  level
0     1.000         0.007984     0.000838      0.065469      0
1     0.375         0.010382     0.033631      0.351733      0
2     0.225         0.008084     0.002696      0.065469      2
3     0.475         0.009114     0.000401      0.046213      0
4     1.000         0.004745     0.001640      0.033376      2
...     ...              ...          ...           ...    ...
3673  0.500         0.003867     0.000510      0.026958      0
3674  0.125         0.001138     0.000109      0.053915      1
3675  0.200         0.001908     0.006158      0.061617      0
3676  0.250         0.001116     0.001130      0.048780      0
3677  0.225         0.003350     0.001312      0.025674      1

[3678 rows x 5 columns]


In [173]:
presentase_test_training = 90/100.0
norm_data_courses['training'] = np.random.rand(len(norm_data_courses)) < presentase_test_training
print(norm_data_courses)

      price  num_subscribers  num_reviews  num_lectures  level  training
0     1.000         0.007984     0.000838      0.065469      0      True
1     0.375         0.010382     0.033631      0.351733      0      True
2     0.225         0.008084     0.002696      0.065469      2     False
3     0.475         0.009114     0.000401      0.046213      0      True
4     1.000         0.004745     0.001640      0.033376      2     False
...     ...              ...          ...           ...    ...       ...
3673  0.500         0.003867     0.000510      0.026958      0      True
3674  0.125         0.001138     0.000109      0.053915      1      True
3675  0.200         0.001908     0.006158      0.061617      0      True
3676  0.250         0.001116     0.001130      0.048780      0      True
3677  0.225         0.003350     0.001312      0.025674      1      True

[3678 rows x 6 columns]


In [174]:
training_data_courses = norm_data_courses[norm_data_courses.training == True]
training_data_courses = training_data_courses.drop('training', axis=1).sample(frac=1)
print(training_data_courses)

      price  num_subscribers  num_reviews  num_lectures  level
1445  0.150         0.002625     0.000364      0.030809      1
699   0.250         0.012736     0.000364      0.064185      0
1977  0.250         0.000000     0.000000      0.039795      1
943   0.000         0.007880     0.004044      0.069320      0
3553  0.250         0.004708     0.003279      0.064185      0
...     ...              ...          ...           ...    ...
747   0.000         0.002670     0.000474      0.008986      1
1165  0.325         0.000119     0.000219      0.038511      0
3436  0.125         0.006154     0.000364      0.056483      2
1434  0.100         0.001380     0.000182      0.033376      0
329   0.300         0.003600     0.002951      0.012837      2

[3315 rows x 5 columns]


In [175]:
test_data_courses = norm_data_courses[norm_data_courses.training == False]
test_data_courses = test_data_courses.drop('training', axis=1).sample(frac=1)
print(test_data_courses)

      price  num_subscribers  num_reviews  num_lectures  level
1573  0.375         0.013108     0.003972      0.042362      2
2431  0.100         0.000093     0.000036      0.012837      1
120   0.250         0.003927     0.000036      0.053915      0
2978  0.925         0.002108     0.002296      0.043646      0
2882  0.100         0.018801     0.002696      0.014121      1
...     ...              ...          ...           ...    ...
1312  0.000         0.011539     0.001530      0.014121      1
1631  0.100         0.036616     0.000874      0.044929      0
1520  0.150         0.000048     0.000146      0.237484      1
656   0.250         0.008263     0.000874      0.014121      0
3666  0.200         0.003265     0.000219      0.010270      0

[363 rows x 5 columns]


In [176]:
training_inputs = training_data_courses.values[:,:5]
print(training_inputs)

[[1.50000000e-01 2.62528679e-03 3.64365094e-04 3.08087291e-02
  1.00000000e+00]
 [2.50000000e-01 1.27359876e-02 3.64365094e-04 6.41848524e-02
  0.00000000e+00]
 [2.50000000e-01 0.00000000e+00 0.00000000e+00 3.97946085e-02
  1.00000000e+00]
 ...
 [1.25000000e-01 6.15417796e-03 3.64365094e-04 5.64826701e-02
  2.00000000e+00]
 [1.00000000e-01 1.37957705e-03 1.82182547e-04 3.33761232e-02
  0.00000000e+00]
 [3.00000000e-01 3.59954336e-03 2.95135726e-03 1.28369705e-02
  2.00000000e+00]]


In [177]:
target_outputs = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
target_outputs = np.array([target_outputs[int(x)] for x in training_data_courses.values[:,4:5]])
print(training_data_courses.values[:,4:5])
print(target_outputs)


[[1.]
 [0.]
 [1.]
 ...
 [2.]
 [0.]
 [2.]]
[[0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 ...
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]]


In [178]:
jumlah_input = len(training_inputs[0])
jumlah_neuron_hidden_layer = 5
np.random.seed(1)
synaptic_weights_1 = 2 * np.random.random((jumlah_input, jumlah_neuron_hidden_layer))-1

print(synaptic_weights_1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]
 [ 0.34093502 -0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523  0.7527783 ]]


In [179]:
jumlah_output = len(target_outputs[0])
synaptic_weights_2 = 2 * np.random.random((jumlah_neuron_hidden_layer, jumlah_output)) -1
print(synaptic_weights_2)

[[ 0.78921333 -0.82991158 -0.92189043 -0.66033916]
 [ 0.75628501 -0.80330633 -0.15778475  0.91577906]
 [ 0.06633057  0.38375423 -0.36896874  0.37300186]
 [ 0.66925134 -0.96342345  0.50028863  0.97772218]
 [ 0.49633131 -0.43911202  0.57855866 -0.79354799]]


In [180]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [181]:
def sigmoid_derivative(x):
  return x*(1-x)

In [182]:
learning_rate = 0.01
for i in range(50):
  outputs_1 = sigmoid(np.dot(training_inputs, synaptic_weights_1))
  outputs_2 = sigmoid(np.dot(outputs_1, synaptic_weights_2))

  error = (target_outputs - outputs_2)
  error_mean = abs(error).mean()

  adjusment_2 = error * sigmoid_derivative(outputs_2)
  adjusment_1 = adjusment_2.dot(synaptic_weights_2.T) * sigmoid_derivative(outputs_1)

  synaptic_weights_2 += outputs_1.T.dot(adjusment_2) * learning_rate
  synaptic_weights_1 += training_inputs.T.dot(adjusment_1) * learning_rate
print('synaptic weight antara input dan hidden layer setelah training')
print(synaptic_weights_1)

synaptic weight antara input dan hidden layer setelah training
[[ 0.91378474  0.54584513 -0.32525564  1.19685625 -1.21520883]
 [-0.71187756 -0.58664349 -0.22998494 -0.10717052  0.03050179]
 [-0.1293945   0.3866799  -0.57122756  0.8058847  -0.96819719]
 [ 0.57116129 -0.07834463  0.26765723 -0.31889097 -0.77319335]
 [-1.34357565 -1.72473616 -1.14184217 -4.98548193  4.12824407]]


In [183]:
test_inputs = test_data_courses.values[:,:5]
len(test_inputs)
target_outputs = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
target_outputs = np.array([target_outputs[int(x)] for x in test_data_courses.values[:,4:5]])
print(target_outputs)

[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 ...
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [220]:
outputs_1 = sigmoid(np.dot(test_inputs, synaptic_weights_1))
outputs_2 = sigmoid(np.dot(outputs_1, synaptic_weights_2))
print(np.round(outputs_2, 3))
len(outputs_1)

[[0.02  0.687 0.57  0.043]
 [0.045 0.708 0.2   0.018]
 [0.968 0.096 0.001 0.004]
 ...
 [0.048 0.714 0.172 0.016]
 [0.967 0.094 0.001 0.004]
 [0.962 0.102 0.001 0.004]]


363

In [222]:
prediksi = np.around(outputs_2)
discrepancy = np.argmax(prediksi, axis=1) == np.argmax(target_outputs, axis=1)
presentase_benar = np.sum(discrepancy)/len(discrepancy)

hasil_test = test_data_courses[['level']].replace([0, 1, 2, 3], ['All Levels', 'Beginner Level', 'Intermediate Level', 'Expert Level'])
hasil_test['Prediction'] = np.argmax(outputs_2, axis=1)
hasil_test['Prediction'] = hasil_test['Prediction'].replace([0,1,2,3],['All Levels', 'Beginner Level', 'Intermediate Level', 'Expert Level'])

print(hasil_test)
print(' ')
print('Correct: ', sum(discrepancy), '/', len(hasil_test), (presentase_benar*100), '%')

                   level      Prediction
1573  Intermediate Level  Beginner Level
2431      Beginner Level  Beginner Level
120           All Levels      All Levels
2978          All Levels      All Levels
2882      Beginner Level  Beginner Level
...                  ...             ...
1312      Beginner Level  Beginner Level
1631          All Levels      All Levels
1520      Beginner Level  Beginner Level
656           All Levels      All Levels
3666          All Levels      All Levels

[363 rows x 2 columns]
 
Correct:  317 / 363 87.32782369146005 %
